services:
  db:
    image: amazon/dynamodb-local:latest
    container_name: question-ms-db
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath ./data
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal

  app:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: .
          target: .
    container_name: question-ms
    depends_on:
      - db
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}

    ports:
      - "80:80"

volumes:
  dynamodb_data:
