services:
  db:
    image: 'postgres:16.0-alpine'
    environment:
      POSTGRES_USER: ${DB_URL}
      POSTGRES_PASSWORD: ${DB_USER}
      POSTGRES_DB: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: .
          target: .
    container_name: question-ms
    depends_on:
      - db
    environment:

    ports:
      - "80:80"

volumes:
  db_data:
