package com.quemiztry.question_ms.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;
import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Question")
public class Question {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String stem;
    @DynamoDBAttribute
    private List<Option> option;
    private Integer isAnswer;
    private List<Topic> topics;
    private List<Skill> skills;
    private String status;
    private Date publishedOn;
    private String publishedBy;
    private Date closedOn;
    private String closedBy;
    private Date createdOn;
    private String createdBy;

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class Option {
        @DynamoDBAttribute(attributeName = "no")
        private Integer no;

        @DynamoDBAttribute(attributeName = "text")
        private String text;

        @DynamoDBAttribute(attributeName = "explanation")
        private String explanation;

        @DynamoDBAttribute(attributeName = "isAnswer")
        private Boolean isAnswer;
    }


}
