spring:
  application:
    name: question_ms

  data:
    dynamodb:
      entity2ddl:
        gsiProjectionType: ALL
        readCapacity: 10
        writeCapacity: 1

amazon:
  dynamodb:
    endpoint: ${DATABASE_URL}

server:
  port: 80

management:
  endpoint:
    health:
      enabled: true
      show-details: never
  endpoints:
    web:
      base-path: /v1
      path-mapping:
        health: /questions/actuator

