spring:
  application:
    name: question_ms

  data:
    dynamodb:
      entity2ddl:
        gsiProjectionType: ALL
        readCapacity: 10
        writeCapacity: 1

amazon:
  dynamodb:
    endpoint: ${DATABASE_URL}
  aws:
    accesskey: ${AWS_ACCESS_KEY}
    secretkey: ${AWS_SECRET_KEY}
    region:
      static: ap-southeast-1
