spring:
  application:
    name: question_ms

  data:
    dynamodb:
      entity2ddl:
        gsiProjectionType: ALL
        readCapacity: 10
        writeCapacity: 1

amazon:
#  dynamodb:
#    endpoint: https://dynamodb.ap-southeast-1.amazonaws.com
  aws:
    accesskey: ${AWS_ACCESS_KEY_ID}
    secretkey: ${AWS_SECRET_ACCESS_KEY}
    region: ap-southeast-1

server:
  port: 80

management:
  endpoint:
    health:
      enabled: true
      show-details: never
  endpoints:
    web:
      base-path: /v1
      path-mapping:
        health: /questions/actuator

logging:
  level:
    javax.net.ssl: DEBUG