package com.quemistry.question_ms.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverter;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.IOException;
import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Option")
public class Topic {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "name")
    private String name;


    public static class TopicListConverter implements DynamoDBTypeConverter<String, List<Topic>> {
        private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();

        @Override
        public String convert(List<Topic> topics) {
            try {
                return OBJECT_MAPPER.writeValueAsString(topics);
            } catch (JsonProcessingException e) {
                throw new RuntimeException("Error converting list of topics to JSON string", e);
            }
        }

        @Override
        public List<Topic> unconvert(String json) {
            try {
                return OBJECT_MAPPER.readValue(json, OBJECT_MAPPER.getTypeFactory().constructCollectionType(List.class, Topic.class));
            } catch (IOException e) {
                throw new RuntimeException("Error converting JSON string to list of topics", e);
            }
        }
    }

}
