#!/bin/bash

echo "***** Git Precommit: Running unit tests ******"
echo $JAVA_HOME
java -version
#git stash -q --keep-index

./gradlew test

status=$?

#git stash pop -q

echo "*****  Git Precommit: Done with unit tests ******"

exit $status